// Add a new project by adding one object here — the card renders automatically.
const PROJECTS = [
  {
    slug: "jeoprady",
    title: "Larprady!",
    description: "A multi-team Jeopardy game with 600 real episodes, a custom board builder, and a growing library of original modern/nostalgia categories.",
    tags: ["game", "trivia", "js"],
    accent: "#ffcc00",
    accentBg: "linear-gradient(135deg, #060ce9 0%, #020556 100%)",
    href: "jeoprady/",
    status: "live",
  },
  {
    slug: "wishlist",
    title: "Wishlist",
    description: "Paste any product link and it unfurls into a clean card — title, image, and price scraped automatically.",
    tags: ["tool", "node", "js"],
    accent: "#3f7d5a",
    accentBg: "linear-gradient(135deg, #f8f6f1 0%, #e4ddd2 100%)",
    href: "wishlist/",
    status: "live",
  },
  {
    slug: "chameleon",
    title: "Meccha Chameleon",
    description: "A blank figure is hiding in today's photo. Find it as fast as you can — your time and your click count are the only score. One a day.",
    tags: ["game", "daily", "js"],
    accent: "#ffffff",
    accentBg: "linear-gradient(135deg, #e23b2e 0%, #7b1e14 100%)",
    href: "chameleon/",
    status: "live",
  },
  {
    slug: "white-canvas",
    title: "White Canvas",
    description: "A shared pixel wall. Everyone draws on the same canvas, live — and every pixel stays.",
    tags: ["toy", "realtime", "js"],
    accent: "#003eff",
    accentBg: "linear-gradient(135deg, #ffffff 0%, #e6e4e0 100%)",
    href: "white-canvas/",
    status: "live",
  },
  {
    slug: "translate",
    title: "Lost in Translation",
    description: "A phrase in a mystery language. Guess what it means \u2014 and which language it is.",
    tags: ["game", "language", "js"],
    accent: "#1a73e8",
    accentBg: "linear-gradient(135deg, #ffffff 0%, #e8f0fe 100%)",
    href: "translate/",
    status: "live",
  },
];
